baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'BVSLN Services'

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: G-YBJ789VB30

plugins:
  - jekyll-environment-variables
